- src/main/java/com/developers/live/developers/mentoring/controller/RoomController.java
- src/main/java/com/developers/live/developers/mentoring/dto/RoomAddRequestDto.java
- src/main/java/com/developers/live/developers/mentoring/dto/RoomEnterRequestDto.java
- src/main/java/com/developers/live/developers/mentoring/dto/RoomListResponseDto.java
- src/main/java/com/developers/live/developers/mentoring/entity/Room.java
- src/main/java/com/developers/live/developers/mentoring/repository/RoomRepository.java
- src/test/java/com/developers/live/developers/repository/RoomRepositoryTest.java
- src/test/java/com/developers/live/developers/service/RoomServiceTest.java
- 멘토링룸 생성 및 조회 기능 개발
<br>
- 멘토링룸을 생성하는 API와 조회하는 API를 개발했습니다.
- 멘토링룸 목록 조회에서 검색기능은 LIKE 로 개발했습니다.
<br>
- @paduck-96 
- @Jooney-95 
close #1
close #2
> feat: Mentoring Room API develop

- build.gradle
- src/docs/asciidoc/index.adoc
- src/main/java/com/developers/live/mentoring/controller/RegisterController.java
- src/main/java/com/developers/live/mentoring/controller/RoomController.java
- src/main/java/com/developers/live/mentoring/controller/ScheduleController.java
- src/main/java/com/developers/live/mentoring/dto/RoomAddRequestDto.java
- src/main/java/com/developers/live/mentoring/dto/RoomGetDto.java
- src/main/java/com/developers/live/mentoring/dto/ScheduleAddRequestDto.java
- src/main/java/com/developers/live/mentoring/entity/Room.java
- src/main/java/com/developers/live/mentoring/service/CachingRoomService.java
- src/main/java/com/developers/live/mentoring/service/RoomService.java
- src/main/java/com/developers/live/mentoring/service/RoomServiceImpl.java
- src/main/java/com/developers/live/mentoring/service/ScheduleServiceImpl.java
- src/main/resources/static/docs/index.html
- src/test/java/com/developers/live/controller/RegisterControllerTest.java
- src/test/java/com/developers/live/controller/RoomControllerTest.java
- src/test/java/com/developers/live/controller/ScheduleControllerTest.java
- src/test/java/com/developers/live/repository/RoomRepositoryTest.java
- src/test/java/com/developers/live/repository/ScheduleRepositoryTest.java
- src/test/java/com/developers/live/service/RegisterServiceTest.java
- src/test/java/com/developers/live/service/RoomServiceTest.java
- src/test/java/com/developers/live/service/ScheduleServiceTest.java
- controller, service 단의 테스트 코드 작성
<br>
- `@MockMvc`를 이용해 controller 단의 테스트를 진행했습니다.
<br>
- @kcs-developers/start-dream-team 
close #24
> test: controller, service test

- src/docs/asciidoc/index.adoc
- src/main/java/com/developers/live/mentoring/controller/RoomController.java
- src/main/java/com/developers/live/mentoring/repository/RoomRepository.java
- src/main/java/com/developers/live/mentoring/service/RoomService.java
- src/main/java/com/developers/live/mentoring/service/RoomServiceImpl.java
- src/main/resources/static/docs/index.html
- src/test/java/com/developers/live/controller/RoomControllerTest.java
- src/test/java/com/developers/live/controller/ScheduleControllerTest.java
- 메인 화면에서 가장 최근에 만들어진 방 10개 조회 API 개발
<br>
- 메인에서 보여지는 최신 방 목록에 대해서는 바로 DB에서 최신순 10개를 정렬 후 가져오도록 구현했습니다.
<br>
> feat: 최신순 정렬 후 10개의 방 조회 및 controller test 진행

- Dockerfile
- Jenkinsfile
- dockerfile, jenkinsfile 수정
<br>
- dockerfile, jenkinsfile 수정
<br>
- @kcs-developers/start-dream-team @paduck-96
> fix: dockerfile, jenkinsfile

- src/docs/asciidoc/index.adoc
- src/main/resources/static/docs/index.html
- src/test/java/com/developers/live/mentoring/repository/RoomRepositoryTest.java
- src/test/java/com/developers/live/mentoring/repository/ScheduleRepositoryTest.java
- src/test/java/com/developers/live/session/SessionServiceTest.java
- submodule 설정
<br>
- submodule 설정
<br>
- @kcs-developers/start-dream-team @paduck-96
> fix: submodule

- src/test/java/com/developers/live/mentoring/repository/RoomRepositoryTest.java
- src/test/java/com/developers/live/mentoring/repository/ScheduleRepositoryTest.java
- test의 properties 설정 변경
<br>
- test의 properties 설정 변경 (`local` -> `live-prod`)
<br>
- @kcs-developers/start-dream-team @paduck-96
> fix: test properties

- src/docs/asciidoc/index.adoc
- src/main/resources/static/docs/index.html
- fix asciidocs snippets
<br>
- fix asciidocs snippets
<br>
> fix: asciidocs snippets

- src/main/resources/application.yml
- fix: application properties yml
<br>
- fix: application properties yml
<br>
> fix: application properties yml

- src/main/java/com/developers/live/mentoring/service/CachingRoomService.java
- src/main/java/com/developers/live/mentoring/service/RoomService.java
- src/main/java/com/developers/live/mentoring/service/ScheduleService.java
- fix: hostname
<br>
- fix: hostname
<br>
> fix: hostname

- src/main/java/com/developers/live/session/controller/DailyCoController.java
- src/main/java/com/developers/live/session/dto/SessionRedisRemoveRequest.java
- src/main/java/com/developers/live/session/dto/SessionRedisSaveRequest.java
- src/main/java/com/developers/live/session/dto/dailyco/DailyCoCreateRequest.java
- src/main/java/com/developers/live/session/dto/dailyco/DailyCoDeleteRequest.java
- src/main/java/com/developers/live/session/service/DailyCoService.java
- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- 검징 로직 추가
<br>
- Dailyco enter 요청은 멘토만 가능하게 수정하였습니다
- 방 입장(Redis Session)에 저장 은 해당 스케쥴의 사용자와 현재 멤버를 비교해 진행하게 수정하였습니다
- (클라이언트에서는 이 부분을 참고해 작성하면 될 것 같습니다)
<br>
- @kcs-developers/start-dream-team @soojik
> fix: 검증 로직 일부 추가 구현

- src/main/java/com/developers/live/config/WebConfig.java
- cors 설정 수정
<br>
- 지정 클라이언트 도메인
- credentials 허용
<br>
-
> fix: cors 오류 수정

- src/main/java/com/developers/live/config/RedisConfig.java
- live-prod.yml 수정
<br>
-
<br>
-
> fix: live-prod.yml modify:

- src/main/java/com/developers/live/config/RedisConfig.java
- redisconfig 수정
<br>
-
<br>
-
> fix: elastic cache

- src/main/java/com/developers/live/config/RedisConfig.java
-엘라스틱 캐시를 위한 config 수정
<br>
- 클러스터 타입으로 변경하였습니다
<br>
-
> fix: 엘라스틱 캐시를 위한 config 수정

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
-세션 입장 로직 수정
<br>
- 세션 입장 시 스케쥴에서 멘토, 멘티 아이디를 비교하는 로직을 수정하였습니다
<br>
- @kcs-developers/start-dream-team @soojik
> fix: 세션 입장 로직 수정

- src/main/java/com/developers/live/session/dto/dailyco/DailyCoCreateRequest.java
- dailyco request dto 수정
<br>
-
<br>
-
> fix: dailyco request dto modify

- src/main/java/com/developers/live/GlobalExceptionHandler.java
- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
> fix: exception modify:

- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- src/main/resources/application.yml
- dailyco api 로직 수정
<br>
- request 객체를 수정하였습니다
<br>
- @soojik
> fix: dailyco api 로직 수정

- src/main/resources/application.yml
- application properties 수정
<br>
- `local` -> `prod`
<br>
> fix: application properties

- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- dailyco 전달 객체 수정
<br>
-
<br>
-
> fix: dailyco 전달 객체 수정

- src/main/java/com/developers/live/session/dto/SessionRedisSaveResponse.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
> fix: enter 응답 수정

- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- session delete 로직 수정
<br>
-
<br>
-
> fix: session delete 수정

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- redis template 수정
<br>
- 정상적 문자열 등록이 되게 수정하였습니다
<br>
-
> fix: redis template 수정

- src/main/java/com/developers/live/session/dto/SessionRedisRemoveRequest.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: dailyco 삭제 방 이름
<br>
- dailyco 삭제시 필요한 방 이름 전달 수정하였습니다
<br>
> fix: dailyco 삭제 방 이름

- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- fix: dailyco api key 수정
<br>
- .yml로 등록
<br>
> fix: dailyco api key 수정

- src/main/java/com/developers/live/session/dto/dailyco/DailyCoResponse.java
- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- fix: dailyco delete modify
<br>
- fix: dailyco delete modify
<br>
-
> fix: dailyco delete modify

- src/main/java/com/developers/live/config/RedisConfig.java
- fix: redis config 수정
<br>
- fix: redis config 수정하였습니다
<br>
- @kcs-developers/start-dream-team @soojik
> fix: redis config 수정

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: enter logging add
<br>
- fix: enter logging add
<br>
-
> fix: enter logging add

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- enter modify
<br>
- enter modify 로직 수정하였습니다
- 
<br>
-
> fix: enter modify

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: string value
<br>
- fix: string value 수정 
<br>
-
> fix: string value

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: logging
<br>
- fix: logging 레디스 반환 값 확인
<br>
-
> fix: logging

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: server login change
<br>
- fix: server login change
<br>
-
> fix: server login change

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: dailyco create
<br>
- fix: dailyco create 수정
<br>
-
> fix: dailyco create

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: null compare
<br>
- fix: null compare
<br>
-
> fix: null compare

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fixL enter log
<br>
- fixL enter log
<br>
-
> fixL enter log

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: decoding add
<br>
- fix: decoding add 하여 객체 디코딩
<br>
-
> fix: decoding add

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: session se/dese
<br>
- fix: session se/dese
<br>
-
> fix: session se/dese

- src/main/java/com/developers/live/config/RedisConfig.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: redis config modify
<br>
- fix: redis config modify 수정
<br>
-
> fix: redis config modify

- src/main/java/com/developers/live/config/RedisConfig.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: redis config change
<br>
- fix: redis config change
<br>
-
> fix: redis config change

- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: loging 수정
<br>
- fix: loging 수정
<br>
-
> fix: loging 수정

- src/main/java/com/developers/live/session/dto/SessionRedisSaveRequest.java
- src/main/java/com/developers/live/session/service/DailyCoService.java
- src/main/java/com/developers/live/session/service/DailyCoServiceImpl.java
- src/main/java/com/developers/live/session/service/SessionServiceImpl.java
- fix: session enter && delete modify
<br>
- 방 입장 시 dailyco에 속성 추가할 수 있게 dto 수정하였습니다
- 방 입장 시 redis에 저장되는 모든 값에 60분 이후 자동 삭제 값 추가하였습니다
- 방 삭제 시 방-방 url 과 방-사용자 모두 삭제되게 수정하였습니다
<br>
- @kcs-developers/start-dream-team @soojik
> fix: session enter && delete modify
